name: Java CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: build and test cadc-dali
      run: cd cadc-dali && ../gradlew --info clean build javadoc checkstyleMain install
      
# cadc-dali-pg is not yet cleanup to pass checkstyleMain
    - name: build and test cadc-dali-pg
      run: cd cadc-dali-pg && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-sia
      run: cd cadc-sia && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-datalink
      run: cd cadc-datalink && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test cadc-datalink-server
      run: cd cadc-datalink-server && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-pkg-server
      run: cd cadc-pkg-server && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test cadc-soda-server
      run: cd cadc-soda-server && ../gradlew --info clean build javadoc checkstyleMain install

    - name: install wcslib
      run: sudo apt-get install -y wcslib

    - name: build and test cadc-data-ops-fits
      run: cd cadc-data-ops-fits && ../gradlew --info clean build javadoc checkstyleMain install
